name: Test Documentation Links

on:
    pull_request:
        paths:
            - 'doc/**'
    push:
        branches:
            - main
        paths:
            - 'doc/**'

permissions:
    issues: write
    contents: read
    pull-requests: write

jobs:
    link-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Install and run lychee
              uses: lycheeverse/lychee-action@v2
              with:
                  args: --verbose --no-progress --fallback-extensions md,mdx --include-wikilinks 'doc/'
              continue-on-error: true
              id: lychee

            - name: Save link check report
              if: steps.lychee.outcome == 'failure'
              run: |
                  mkdir -p reports
                  cp lychee/out.md reports/link-check-report.md 2>/dev/null || echo "No report file found" > reports/link-check-report.md

            - name: Create/Update issue
              if: steps.lychee.outcome == 'failure'
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  title="Broken links detected in documentation"
                  num=$(gh issue list -S "in:title \"$title\" is:open" -L 1 --json number -q ".[0].number")
                  if [ -n "$num" ]; then
                    echo "Updating existing issue #$num"
                    gh issue edit "$num" --body-file reports/link-check-report.md
                  else
                    echo "Creating new issue"
                    gh issue create --title "$title" --body-file reports/link-check-report.md --label documentation --assignee tt-tom17
                  fi