name: Test Documentation Links

on:
  pull_request:
    paths:
      - 'doc/**'
  push:
    branches:
      - main
    paths:
      - 'doc/**'

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --exclude-mail 'doc/'

      - name: Save link check report
        if: always()
        run: |
          mkdir -p reports
          mv lychee/out.md reports/link-check-report.md || true

      - name: Upload report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: link-check-report
          path: reports/link-check-report.md